##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [4.2.0-B44] date: [Sat Apr 27 17:51:16 CEST 2024]
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = 01_mobot_stm32g474_cubeGenerate


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES =  \
src/main.c \
src/drivers/gpio.c \
src/drivers/i2c.c \
src/drivers/spi.c \
src/drivers/tim.c \
src/drivers/usart.c \
src/drivers/stm32g4xx_hal_msp.c \
src/sys/stm32g4xx_it.c \
src/sys/system_stm32g4xx.c \
lib/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_i2c.c \
lib/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_i2c_ex.c \
lib/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal.c \
lib/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_rcc.c \
lib/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_rcc_ex.c \
lib/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_flash.c \
lib/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_flash_ex.c \
lib/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_flash_ramfunc.c \
lib/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_gpio.c \
lib/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_exti.c \
lib/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_dma.c \
lib/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_dma_ex.c \
lib/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_pwr.c \
lib/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_pwr_ex.c \
lib/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_cortex.c \
lib/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_spi.c \
lib/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_spi_ex.c \
lib/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_tim.c \
lib/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_tim_ex.c \
lib/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_uart.c \
lib/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_uart_ex.c

C_SOURCES_CPPCHECK = \
src/main.c \
src/drivers/gpio.c \
src/drivers/i2c.c \
src/drivers/spi.c \
src/drivers/tim.c \
src/drivers/usart.c \
src/drivers/stm32g4xx_hal_msp.c \
src/sys/stm32g4xx_it.c \
src/sys/system_stm32g4xx.c

# ASM sources
ASM_SOURCES =  \
src/sys/startup_stm32g474xx.s

# ASM sources
ASMM_SOURCES = 


#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
CPPCHECK = cppcheck
FORMAT = clang-format

CPPCHECK_FLAGS = \
	--quiet --enable=all --error-exitcode=1 \
	--inline-suppr \
	--suppress=missingIncludeSystem \
	--suppress=unmatchedSuppression \
	--suppress=unusedFunction \
	$(addprefix -I,$(INC_DIRS_CPPCHECK)) \
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m4

# fpu
FPU = -mfpu=fpv4-sp-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DUSE_HAL_DRIVER \
-DSTM32G474xx


# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES =  \
-Isrc/ \
-Isrc/sys \
-Isrc/drivers \
-Isrc/app \
-Ilib/STM32G4xx_HAL_Driver/Inc \
-Ilib/STM32G4xx_HAL_Driver/Inc/Legacy \
-Ilib/CMSIS/Device/ST/STM32G4xx/Include \
-Ilib/CMSIS/Include

C_INCLUDES_CPPCHECK = \
-Isrc/ \
-Isrc/sys \
-Isrc/drivers \
-Isrc/app \

# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS += $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = src/sys/STM32G474CETx_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = 
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASMM_SOURCES:.S=.o)))
vpath %.S $(sort $(dir $(ASMM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@
$(BUILD_DIR)/%.o: %.S Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir $@		

#######################################
# clean up
#######################################
clean:
	-rm -fR $(BUILD_DIR)

cppcheck:
	@${CPPCHECK} ${CPPCHECK_FLAGS} ${C_SOURCES_CPPCHECK}

format:
	@${FORMAT} -i --style=file ${C_SRCS_CPPCHECK} ${INC_FILES_FORMAT}

.PHONY: all clean
  
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***